"""Self-contained HTML audit report generation."""
from html import escape
from typing import Any


def _percent(value: float | None) -> str:
    return "n/a" if value is None else f"{value * 100:.1f}%"


def _attribute_table(attribute: dict[str, Any]) -> str:
    rows = "".join(
        f"<tr><td>{escape(str(group['group']))}{' ⚠' if group['low_n'] else ''}</td>"
        f"<td>{group['n']}</td><td>{group['selected']}</td>"
        f"<td>{_percent(group['selection_rate'])}</td>"
        f"<td>{_percent(group['selection_rate_ci']['low'])}–{_percent(group['selection_rate_ci']['high'])}</td>"
        f"<td>{_percent(group['tpr'])}</td></tr>"
        for group in attribute["groups"]
    )
    test = attribute.get("statistical_test")
    significance = (
        f"p={test['p_value']:.4g}; {'significant' if test['significant_at_0_05'] else 'not significant'}"
        if test
        else "not available"
    )
    return (
        f"<section><h2>{escape(attribute['attribute'].replace('_', ' ').title())}</h2>"
        f"<div class='chips'><b>DI {attribute['disparate_impact']}</b>"
        f"<b>Parity gap {attribute['parity_gap']}</b>"
        f"<b>Eq. opportunity {attribute['eq_opp_gap'] if attribute['eq_opp_gap'] is not None else 'n/a'}</b>"
        f"<b>{escape(significance)}</b></div>"
        "<table><thead><tr><th>Group</th><th>n</th><th>Selected</th><th>Rate</th>"
        f"<th>95% CI</th><th>TPR</th></tr></thead><tbody>{rows}</tbody></table></section>"
    )


def render_html_report(audit: dict[str, Any], chaos: dict[str, Any] | None = None) -> str:
    certificate = audit["certificate"]
    name = escape(str(audit.get("audit_name", "ChaosHire model audit")))
    identity = escape(str(audit.get("audit_id", "reference-demo")))
    created = escape(str(audit.get("created_at", "deterministic reference run")))
    primary = "".join(_attribute_table(attribute) for attribute in audit["attributes"])
    intersections = "".join(_attribute_table(attribute) for attribute in audit.get("intersections", []))
    chaos_html = ""
    if chaos:
        tests = "".join(
            f"<tr><td>{escape(test['name'])}</td><td>{escape(test['value'])}</td>"
            f"<td class='{test['verdict'].lower()}'>{test['verdict']}</td></tr>"
            for test in chaos["tests"]
        )
        chaos_html = (
            "<section><h2>Chaos Lab</h2>"
            f"<p>Experiment <code>{escape(chaos['experiment_id'])}</code> · "
            f"Resilience <b>{chaos['resilience']}/100</b></p>"
            f"<table><tr><th>Test</th><th>Result</th><th>Verdict</th></tr>{tests}</table></section>"
        )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>{name} — ChaosHire report</title><style>
body{{font:15px/1.5 system-ui,sans-serif;color:#172033;max-width:1050px;margin:0 auto;padding:32px}}
header{{border-bottom:4px solid #0ea5e9;padding-bottom:20px}}h1{{margin:0}}h2{{margin-top:30px}}
.summary{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:24px 0}}
.card{{border:1px solid #d7dfeb;border-radius:12px;padding:14px}}.big{{font-size:28px;font-weight:800}}
table{{border-collapse:collapse;width:100%;margin-top:10px}}th,td{{text-align:left;padding:8px;border-bottom:1px solid #d7dfeb}}
.chips{{display:flex;gap:8px;flex-wrap:wrap}}.chips b{{background:#eef6ff;padding:5px 9px;border-radius:20px}}
.pass{{color:#087f5b;font-weight:700}}.warn{{color:#a16207;font-weight:700}}.fail{{color:#be123c;font-weight:700}}
.notice{{background:#fff7ed;border:1px solid #fdba74;padding:12px;border-radius:10px}}code{{background:#eef2f7;padding:2px 5px}}
@media print{{body{{padding:0}}section{{break-inside:avoid}}}}
</style></head><body><header><h1>ChaosHire Audit Report</h1><p><b>{name}</b><br>ID: {identity} · Created: {created}</p></header>
<div class="summary"><div class="card"><div class="big">{audit['stats']['candidates']}</div>Candidates</div>
<div class="card"><div class="big">{audit['stats']['accepted']}</div>Accepted</div>
<div class="card"><div class="big">{certificate['total']} / {certificate['grade']}</div>Fairness Risk Score</div>
<div class="card"><div class="big">{len(audit.get('intersections', []))}</div>Intersection audits</div></div>
<p class="notice"><b>Interpretation notice:</b> This is an exploratory technical assessment, not legal advice or an official certification. Statistical significance does not establish causation. Synthetic reference results are not findings about a real employer.</p>
<h1>Primary attributes</h1>{primary}<h1>Intersectional analysis</h1>{intersections or '<p>Not available.</p>'}{chaos_html}
<footer><hr><p>Generated by ChaosHire · Wilson 95% intervals · four-fifths screening threshold · aggregate evidence only.</p></footer>
</body></html>"""
